his qilib qo'yorasiz
SardorSohinazarov/Product_API pull request #3
Opened 2024-02-13 09:42 UTC by tursunboev

2024-02-13 09:45 UTC, tursunboev commented
Yopildi

2024-02-13 09:58 UTC, Tohirjon-Odilov approved these changes
Qoyil lekin

2024-02-13 09:58 UTC, Tohirjon-Odilov commented on Product_API/Repositories/IProductPostgressRepository.cs
> +                    using NpgsqlCommand cmd = new NpgsqlCommand(@$"insert into products(Name,Description,PhotoPath) values ('{product.Name}','{product.Description}','{product.PhotoPath}') ", connecti
Faqat shu table mavjud bo'lmasa ishkal bo'larkanda

2024-02-13 09:58 UTC, Tohirjon-Odilov commented on Product_API/Repositories/IProductPostgressRepository.cs
> +                connection.Open();
Shu baribir using ichida open qilib ochilishiga tushnmadim

2024-02-13 11:03 UTC, dilshodbek-abdullayev commented on Product_API/Repositories/IProductPostgressRepository.cs
> +        public  string ConnectionString = "Host=localhost;Port = 5432;Database = Lesson;User Id = postgres;Password = root;";
chota bo'mapti manga yoqmadi 😏

2024-02-13 18:01 UTC, Tohirjon-Odilov requested changes

2024-02-13 18:01 UTC, Tohirjon-Odilov commented on Product_API/Repositories/IProductPostgressRepository.cs
> +                    using NpgsqlCommand cmd = new NpgsqlCommand(@$"select username from users ", connection);
usernama nima uchun kerak ekanligini ayta olasizmi va users table'ga necchi endi

2024-02-14 01:48 UTC, OzodbekOlimjonov1411 approved these changes
Siiuuuuuuuuuuuuuuuu

2024-02-14 17:20 UTC, closed without merging