info: update
SardorSohinazarov/Product_API pull request #7
Opened 2024-02-13 11:11 UTC by Akramjon009

2024-02-13 17:06 UTC, AcciGen reviewed
Gap yo'q

2024-02-13 17:06 UTC, AcciGen commented on Product_API/Repositories/IProductPostgressRepository.cs
> +                    using NpgsqlCommand cmd = new NpgsqlCommand(@$"select * from users ", connection);
users👍

2024-02-13 17:15 UTC, AcciGen approved these changes
Gap Yo'q lekin ⚡👍🔥💥

2024-02-13 17:20 UTC, Tohirjon-Odilov requested changes

2024-02-13 17:20 UTC, Tohirjon-Odilov commented on Product_API/Repositories/IProductPostgressRepository.cs
> +                    using NpgsqlCommand cmd = new NpgsqlCommand(@$"select * from users ", connection);
User boʻlmaydi products boʻladi
😁
![Screenshot_2024-02-13-22-20-00.png](https://github.com/SardorSohinazarov/Product_API/assets/82634626/7771242c-f3ba-4cef-a626-bcdd0489e3dd)

2024-02-13 17:21 UTC, Tohirjon-Odilov reviewed
![Screenshot_2024-02-13-22-20-00.png](https://github.com/SardorSohinazarov/Product_API/assets/82634626/6ec9675c-44f6-4c44-a865-1182295a1ebc)

User emas products boʻladi jigar 😁

2024-02-13 17:25 UTC, Akramjon009 commented on Product_API/Repositories/IProductPostgressRepository.cs
> +                    using NpgsqlCommand cmd = new NpgsqlCommand(@$"select * from users ", connection);
yahshiroq qareng menda unaqamasu

2024-02-14 01:01 UTC, closed without merging

2024-02-14 01:01 UTC, SardorSohinazarov commented
Gap yo'q